export const CATEGORIES = [
  "Academia",
  "Agência de Marketing",
  "Artesanato",
  "Autopeças",
  "Bar",
  "Barbearia",
  "Cafeteria",
  "Casa de Festas",
  "Cinema",
  "Clínica de Estética",
  "Clínicas",
  "Comida Japonesa",
  "Concessionária",
  "Contabilidade",
  "Cabeleireiro",
  "Cursos e Treinamentos",
  "Dentista",
  "Depósito de Bebida",
  "Distribuidora",
  "Eletrônicos",
  "Empresas de Segurança",
  "Empresas de TI",
  "Engenharia e Arquitetura",
  "Escola",
  "Escola de Dança",
  "Estética Automotiva",
  "Farmácia",
  "Floricultura",
  "Fotografia",
  "Funilaria e Pintura",
  "Gráfica",
  "Hotel",
  "Imobiliária",
  "Importadora",
  "Informática",
  "Joalheria",
  "Laboratório",
  "Lanchonete",
  "Lavanderia",
  "Livraria e Papelaria",
  "Loja de Calçados",
  "Loja de Móveis",
  "Loja de Roupas",
  "Loja Infantil",
  "Lojas de Utilidades",
  "Manutenção Residencial",
  "Material de Construção",
  "Mecânica",
  "Mercado",
  "Moda Fitness",
  "Mototáxi / Transporte",
  "Nutricionista",
  "Oficina",
  "Padaria",
  "PetShop",
  "Pizzaria",
  "Plano de Saúde",
  "Ponto de Recarga",
  "Pousada",
  "Produtos Naturais",
  "Psicólogo",
  "Restaurante",
  "Salão de Beleza",
  "Serralheria",
  "Serviços Domésticos",
  "Sorveteria",
  "Supermercado",
  "Telefonia",
  "Turismo",
  "Veterinário",
  "Outros",
  "Todos"
];
