export const CATEGORIES = [
  "Autopeças",
  "Bar",
  "Cinema",
  "Clínicas",
  "Dentista",
  "Depósito de bebida",
  "Farmácia",
  "Gráfica",
  "Hotel",
  "Imobiliária",
  "Informática",
  "Lanchonete",
  "Laboratório",
  "Mercado",
  "Oficina",
  "PetShop",
  "Produtos naturais",
  "Restaurante",
  "Roupas",
  "Pousada",
  "Veterinário",
  "Outros",
  "Todos"
];
