export const CATEGORIES = [
    "Todos",
    "Restaurante",
    "Hotel",
    "Pousada",
    "Mercado",
    "Farmácia",
    "Cinema",
    "Bar",
    "PetShop",
    "Veterinario",
    "Imobiliaria",
    "Oficina",
    "Autopeças",
    "Dentista",
    "Laboratório",
    "Clínicas",
    "Roupas",
    "Produtos naturais",
    "Deposito de bebida",
    "Gráfica",
    "Outros"
  ];